name: 'Branch Build'
on:
  pull_request:
jobs:
  branch-build:
    name: Branch Build
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Building the Branch
        run: |
          echo "Building ... $GITHUB_REF"
          echo "The PR number is ${{ github.event.number }}"
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout Code
        run: echo "Running branch.yaml"
      - uses: actions/checkout@v2
