name: 'Main Build - no autoupdate'
on:
  push:
    branches:
      - main
jobs:
  branch-build:
    name: Branch Build
    runs-on: ubuntu-latest
    steps:
      - name: Building the Branch
        run: |
          echo "Building ... $GITHUB_REF"
          echo "The PR number is ${{ github.event.number }}"
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Code
        run: echo "Running main.yaml"
      - uses: actions/checkout@v2
