name: 'Main Build2'
on:
  push:
    branches:
      - main
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.WORKFLOW_TOKEN }}'
          PR_FILTER: 'labelled'
          PR_LABELS: 'auto-update'
          MERGE_MSG: 'all hail our robot overlords, branch has been synced with latest main'
          DRY_RUN: 'false'
          MERGE_CONFLICT_ACTION: 'ignore'

  branch-build:
    name: Branch Build
    needs: autoupdate
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Building the Branch
        run: |
          echo "Building ... $GITHUB_REF"
          echo "The PR number is ${{ github.event.number }}"
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Code
        run: echo "Running main.yaml"
      - uses: actions/checkout@v2
